package chapter3.reinforcement.problem01;

import java.util.Arrays;

/** R-3.1 Give the next five pseudorandom numbers generated by the process described on
 page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
  formula = next = (a ∗ cur + b) % n; */
public class PseudoRandom {
    private int seed = 92;
    private int a = 12;
    private int b = 5;
    private int n = 100;
    private int next;
    private int current;

    int[] randomList = new int[5];

    public PseudoRandom() {

    }

    public void setSeed(int seed) {
        this.seed = seed;

        current = seed;
        for (int i = 0; i < randomList.length; i++) {
            next = ((a * current + b) % n);
            randomList[i] = next;
            current = next;
        }
    }

    public int[] getRandomList() {
        return randomList;
    }

    public static void main(String[] args) {

        PseudoRandom random = new PseudoRandom();
        random.setSeed(10204);
        int[] results = random.getRandomList();
        System.out.println("Five pseudo random numbers: " + Arrays.toString(results));
    }
}
